### ISSUE TITLE
Patch can't diff the same tagName element?

### ISSUE THREAD

**Issue by musicode** [snabbdom/snabbdom#216] opened 2017-01-04 05:58 UTC
look at the mustache template below:

```html
<div id="root">
    {{#if open}}
        <div>
            <div on-click="set('open', false)">
                close
            </div>
        </div>
    {{/if}}
    <div on-click="set('open', true)">
        open
    </div>
</div>
```

when open is `false`, the "open" div is the first child.

when open is `true`,  the "close" div is the first child.

after patch, it is wrong.

but if i use a key, the patch is ok.

```html
<div id="root">
    {{#if open}}
        <div>
            <div on-click="set('open', false)">
                close
            </div>
        </div>
    {{/if}}
    <div key="abc" on-click="set('open', true)">
        open
    </div>
</div>
```

anyone can tell me why and how to fix it ?

**Comment by paldepind** [comment] 2017-02-17 17:23
> after patch, it is wrong.

In what way is it wrong?

I don't see any difference between the first and the last code you posted? Which elements did you put a key property on?

Can you reproduce this in a small code example?

**Comment by musicode** [comment] 2017-02-18 01:35
the last code has a "key", that is the difference.

I guess virtual dom dont know which is the first div, when "open" is true, the inner div is the first, when "open" is false, the outer div is the first.

**Comment by paldepind** [comment] 2017-02-18 10:25
> the last code has a "key", that is the difference.

Oh. Yeah. Now I see it :smile: 

This sounds like a bug. Which I find a bit suprising.

Can you reproduce it with a small code example? That would be very helpful.

**Comment by kuraga** [comment] 2019-12-25 10:45
@mightyiam isn't a bug?

**Comment by mightyiam** [comment] 2019-12-26 12:28
@kuraga thank you for making sure what happens here is clear. I closed this because there's no proof of a bug and no response from the original poster. Should I attempt to reproduce this?

**Comment by kuraga** [comment] 2019-12-26 12:36
@mightyiam I just wanted to understand reason :)

> Can you reproduce it with a small code example? That would be very helpful.

@musicode , ping

And we should think what it could be...

**Comment by paldepind** [comment] 2024-01-23 07:31
Closing, as I don't think there is enough information here to tell what the problem is.

**Closed by paldepind** 2024-01-23 07:31 UTC
Labels: type:bug, affects:user, needs confirmation
