### ISSUE TITLE
Animate entry and removal of elements, using classes and stylesheets

### ISSUE THREAD

**Issue by zenflow** [snabbdom/snabbdom#563] opened 2020-03-10 14:07 UTC
I see that the "style module" supports [Delayed properties](https://github.com/snabbdom/snabbdom#delayed-properties) and [setting properties on `remove`](https://github.com/snabbdom/snabbdom#set-properties-on-remove). 

What are the chances of adding similar features in the "class module"? That is, perhaps a new set of `delayedClass` and `removeClass` options to specify updates that should be made either [respectively] after a delay, or before the element is removed.

This would make it easy to declaratively animate the entry & removal of elements (as the style module does), but *by using classes and stylesheets, instead of by setting styles directly on elements*. I believe this is often preferable for various reasons. Not sure if I need to back up that claim.

If agreed upon, I would be more than happy to implement this and submit a PR!

Thanks!

**Comment by mightyiam** [comment] 2020-03-11 13:28
Sounds good to me, @zenflow. Perhaps an abstraction of the logic used for the style module would be a good idea.

**Comment by mightyiam** [comment] 2020-05-10 11:44
Seems like duplicate of #220 .

**Closed by mightyiam** 2020-05-10 11:44 UTC
