### ISSUE TITLE
Patching should clear out previous root element content

### ISSUE THREAD

**Issue by amirouche** [snabbdom/snabbdom#167] opened 2016-09-29 22:02 UTC
Given the following html:

``` html
  <div id="app">should disappear</div>
```

And the following js code

``` javascript
var patch = snabbdom.init([
    snabbdom_style,
    snabbdom_class,
    snabbdom_props,
    snabbdom_attributes,
    snabbdom_eventlisteners
]);

var vnode = h('div', [" but it", " doesn't"]);
var container = document.getElementById('app');

patch(container, vnode);
```

`patch` will generate the following html:

``` html
<div id="app">should disappear but it doesn't</div>
```

One can work around this by setting an empty id for instance:

``` javascript
var vnode = h('div#', [" but it", " doesn't"]);
```

**Comment by amirouche** [comment] 2016-09-29 22:04
Here is a jsbin http://jsbin.com/sovesitade/1/edit?html,output

**Comment by amirouche** [comment] 2016-09-29 22:05
Also the `id` is wrong

**Comment by amirouche** [comment] 2016-09-30 09:59
It's not possible to reproduce in the test suite. The output of patch is correct but the DOM is not.

**Comment by amirouche** [comment] 2016-09-30 10:27
Here is another bug with similar behavior. With the same html as above, patching the div with the following `vnode`:

```javascript
var vnode = h('div', {attrs: {id: "app"}}, [" but it", " doesn't"]);
```

Won't work.

But the same call with `div#` seem to give the good result.

**Comment by WorldMaker** [comment] 2016-10-19 21:43
This seems to be a regression between 0.5.0 and 0.5.3, if that helps narrow down the cause.

**Comment by paldepind** [comment] 2016-10-22 14:47
Thank you for reporting this @amirouche. Also thanks to @WorldMaker for the additional information.

This is probably related to some recent changes to how `patch` with an element as it's first argument is done.

**Comment by AlexGalays** [comment] 2016-11-07 20:54
Could @staltz help perhaps, since the regression appears to come from that change?

**Comment by staltz** [comment] 2016-11-08 14:30
I'll look into it, but probably after the TypeScript migration.

**Comment by staltz** [comment] 2017-02-09 13:16
Done and released in v0.6.4

**Closed by staltz** 2017-02-09 13:16 UTC
Labels: bug

**Comment by avesus** [comment] 2017-02-28 06:17
Thank you!
