### ISSUE TITLE
package.json lose property of main

### ISSUE THREAD

**Issue by gengqingming** [snabbdom/snabbdom#881] opened 2020-10-14 01:05 UTC
It is a lack of property of main in  package.json of sanbbdom. It reports an error that 'can't find resolve snabbdom' when using a webpack to pack files.

**Comment by mreinstein** [comment] 2020-10-22 19:52
i've run into this too, ideally there would be a `main` property set. Bonus points if it was also a pure es module with `"type": "module"` set in `package.json` too :)

**Comment by JacobChang** [comment] 2020-11-19 13:00
Not sure if it's the same reason, I was using TypeScript and parcel bundler, I need to import code like this

```

import { init } from "snabbdom/build/package/init";

```

**Comment by mreinstein** [comment] 2021-02-15 16:34
I believe this is related to and maybe a duplicate of #913

**Closed** 2021-02-15 16:34 UTC
