### ISSUE TITLE
Out of The Box usage with Webpack

### ISSUE THREAD

**Issue by patomation** [snabbdom/snabbdom#760] opened 2020-08-02 08:29 UTC
# Motivation
I've used Snabbdom a little bit with CycleJS. But recently I'm wanting to use it in a vanilla project to handle dom stuff.
My zipped bundle would need to need to be 13kb. 
My options are to use vanilla JavaScript dom manipulation; which is tedious. 
Or use snabbdom which might be small enough to be worth it. 

# The issue:
I think the issue has something to do with my environment.
I'm having trouble with typescript. I'm also using vs code for what its worth.
The IDE error is as such.
```Cannot find module 'snabbdom/init' or its corresponding type declarations. ts(2307)```
The runtime error is something like this for each module
```
./src/index.ts
Module not found: Error: Can't resolve 'snabbdom/h' in '/home/patrick/source/vanilla-starter/src'
```
My next step is to provide an alias for webpack. The npm_module/snabdom is empty it needs to point to node_modules/snabdom/build. Maybe that will fix it.
So I added this to my webpack config:
```
module.exports = {
...
  resolve: {
    ...
    alias: {
      snabbdom: path.resolve(__dirname, 'node_modules', 'snabbdom', 'build')
    }
  }
}
``` 
That didn't seem to work.

I guess my final thoughts are this.
Shouldn't Snabbdom work better out of the box? Should I be using a different packager?
I would like to understand this library to see what I can do to make this better for new users in the future.

You can see my repo here:
[EXAMPLE REPO](https://github.com/patomation/vanilla-starter/tree/snabbdom)
see ```./src/index.ts``` and ```webpack.config.js```

**Comment by mightyiam** [comment] 2020-08-03 03:14
Duplicate of #516

**Closed by mightyiam** 2020-08-03 03:14 UTC

**Comment by kuraga** [comment] 2020-08-03 06:03
Sorry, is it really a duplicate?

**Comment by mightyiam** [comment] 2020-08-03 10:07
@kuraga, I wrote this comment while sharing screen with @patomation.

**Comment by kuraga** [comment] 2020-08-03 11:46
Well, just #516 is closed so duplicate of it should be already fixed :)
An old old version of code has been used?

**Comment by mightyiam** [comment] 2020-08-03 12:08
More like duplicate of #723.
