### ISSUE TITLE
dangerouslySetInnerHTML?

### ISSUE THREAD

**Issue by avesus** [snabbdom/snabbdom#238] opened 2017-01-30 18:31 UTC
Sometimes it's necessary just to insert bulk of raw HTML. React has the function `dangerouslySetInnerHTML`. How to accomplish the same with Snabbdom?

**Comment by TylorS** [comment] 2017-01-30 18:55
Hello @avesus this is a dupe of #105, but the simple solution is `div({ props: { innerHTML: htmlString } })`.

**Closed** 2017-01-30 19:07 UTC
